// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebServiceRestfull.Data;

#nullable disable

namespace WebServiceRestfull.Migrations.Recompensa
{
    [DbContext(typeof(RecompensaContext))]
    [Migration("20220927021903_CriandoTabelaRecompensa")]
    partial class CriandoTabelaRecompensa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebServiceRestfull.Entities.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ExercicioRealizado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXERCICIOREALIZADO");

                    b.Property<DateTime>("Registro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGISTRO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO");

                    b.Property<int>("Valor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.ToTable("RECOMPENSA");
                });
#pragma warning restore 612, 618
        }
    }
}
